name: Wireshark ESBMC action test workflow

on: push

jobs:
    test-esbmc-action:
        runs-on: ubuntu-latest
        steps:
            - name: Run ESBMC action
              uses: esbmc/esbmc-action@v2
              with:
                esbmc-options: --incremental-bmc --include include/ --include . --include-file config.h
